### PR TITLE
17 ayonapiget does not check for failed httplib connections

### LINKED ISSUE #17: AyonApi::GET() dose not check for failed httplib connections
### Description

When a Httplib connection failed to connect. eg because of wrong ssl certs or similar the status object is outside the memory bounds. 
for this we can do this: 

```cpp
if (!response){
  Log->critical(Log->key("AyonApi"), "AyonApi::GET({})", response.error());
  return nlohmann::json();
}
```

and check the type. 
im not sure if we want this to only Log critical or actually crash as this is not just a wrong return (they are covered with logs and returns) but usually some invalid thing or a connection error all together. 

### Rationale

_No response_

### Proposed Solution

_No response_

### Alternatives Considered

_No response_

### Additional Context

_No response_

### Impact

Low

### Assumed Complexity

Hours

### Impact Scale

no other tool

### Other tools that get touched

_No response_

### Is there an existing issue with this?

- [X] I have searched the existing issues

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### LINKED ISSUE #37: AYON CPP API doesn't support using AYON serivce api key
### Describe the bug

AYON CPP doesn't accept `AYON_API_KEY`. 

### Why is this an issue?

When working with DCC locally, the `AYON_API_KEY` is set to the bearer token.
On the other hand, when working with DCC on farm, the `AYON_API_KEY` is set to the service api key. 

This cause the resolver to fail to login on farm jobs where the `AYON_API_KEY` is set to the service api key. 

### Describe yourself

_No response_

### To Reproduce

_No response_

### How did you discover the bug?

_No response_

### Expected behaviour

_No response_

### Screenshots

_No response_

### Hardware Setup

_No response_

### Software Setup

_No response_

### User Type

_No response_

### Additional Environment Details

_No response_

### What platform are you running on?

Windows 11

### Additional context

_No response_

### Is there an existing issue with this?

- [x] I have searched the existing issues

### Are there any labels you wish to add?

- [x] I have added the relevant labels to the bug report.

### PR DESCRIPTION
**Pull request by tadeas-hejnic**
## Changelog Description
- Fixed connection issues with secured servers  
- Environment variables for testing are no longer hardcoded in source files  
- Cross-platform implementation of `TestServer.py`  

## Additional Review Information
The method for locating the CA CERT file is somewhat unconventional. I explored three alternative approaches since the standard ones didn't work. To ensure robustness, testing on a variety of machines would be beneficial.  

This implementation has been tested on Ubuntu, AlmaLinux, and Windows.  

Note: Some pre-existing typos in the code will be corrected in the next PR.  

## Testing Notes

Test together with resolver against secured server.

~~Follow the steps outlined in the README:~~

1. Run `git submodule update --init --recursive` after switching branches.  
2.  Create `.env_http` and `.env_https` files and populate them with the necessary environment variables:  ~~
   - `AYON_API_KEY`  
   - `AYON_SERVER_URL`  
   - `AYON_PROJECT_NAME`  
   - `AYON_SITE_ID`  
   - I tested with `http://localhost:8003`, which is run by `TestServer.py`.  
   - For testing against a secured server, I used `https://ayon.dev`.  
3.  `python AyonBuild.py --setup`.  ~~
4.  `python AyonBuild.py --runStageGRP CleanBuildAndTest`. ~~

### Expected Output
The first three tests remain unchanged and should pass without issues.

The crucial one is the last test, `AyonCppApiCreationSSL`, it **should not** print:  

[error] Failed to connect to the Ayon server.

### CODE REVIEW

**Review by MustafaJafar — COMMENTED** [review]
Running on windows, 
My setup: I'm using `.env_http` and local AYON instance.
<details><summary><code>.env_http</code> contents</summary>

```
AYON_SERVER_URL=http://AYON_SERVER_IP:PORT/
AYON_API_KEY=veryinsecureapikey
AYON_PROJECT_NAME=Animal_Logic_ALab
AYON_SITE_ID=military-mouse-of-jest
```
</details>

I got this error when running `python AyonBuild.py --runStageGRP CleanBuildAndTest`
```
("Finished Execution with code:1, {'Cmake': ['Error at "
 'build/test/cmake_install.cmake:55 (file):\\n  file INSTALL cannot find\\n  '
 '"E:/Ynput/ayon-cpp-api/build/test/Release/AyonCppApiGtestMain.exe": File\\n  '
 'exists.\\nCall Stack (most recent call first):\\n  '
 "build/cmake_install.cmake:57 (include)']}",)
 ```
 
 
<details><summary>Full Log</summary>

```
E:\Ynput\ayon-cpp-api>git fetch origin 17-ayonapiget-dose-not-check-for-failed-httplib-connections
remote: Enumerating objects: 124, done.
remote: Counting objects: 100% (117/117), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 98 (delta 64), reused 82 (delta 49), pack-reused 0 (from 0)
Unpacking objects: 100% (98/98), 22.56 KiB | 78.00 KiB/s, done.
From https://github.com/ynput/ayon-cpp-api
 * branch            17-ayonapiget-dose-not-check-for-failed-httplib-connections -> FETCH_HEAD
 * [new branch]      17-ayonapiget-dose-not-check-for-failed-httplib-connections -> origin/17-ayonapiget-dose-not-check-for-failed-httplib-connections

E:\Ynput\ayon-cpp-api>git checkout 17-ayonapiget-dose-not-check-for-failed-httplib-connections        
Switched to a new branch '17-ayonapiget-dose-not-check-for-failed-httplib-connections'
M       ayon_automator
M       ext/cpp-httplib
branch '17-ayonapiget-dose-not-check-for-failed-httplib-connections' set up to track 'origin/17-ayonapiget-dose-not-check-for-failed-httplib-connections'.

E:\Ynput\ayon-cpp-api>git submodule update --init --recursive
Submodule 'ext/ayon-cpp-dev-tools' (https://github.com/ynput/ayon-cpp-dev-tools.git) registered for path 'ext/ayon-cpp-dev-tools'
Cloning into 'E:/Ynput/ayon-cpp-api/ext/ayon-cpp-dev-tools'...
Submodule path 'ayon_automator': checked out 'c713f48ba0099158bad034a91b36cb025b72fc15'
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 9 (delta 4), reused 9 (delta 4), pack-reused 0 (from 0)
Unpacking objects: 100% (9/9), 1.27 KiB | 44.00 KiB/s, done.
From https://github.com/ynput/ayon-cpp-dev-tools
 * branch            12d70139791e1386c8a6b643a92d942e84238da4 -> FETCH_HEAD
Submodule path 'ext/ayon-cpp-dev-tools': checked out '12d70139791e1386c8a6b643a92d942e84238da4'
Submodule 'ext/ayon_automator' (https://github.com/ynput/ayon-automator.git) registered for path 'ext/ayon-cpp-dev-tools/ext/ayon_automator'
Submodule 'ext/benchmark' (https://github.com/google/benchmark.git) registered for path 'ext/ayon-cpp-dev-tools/ext/benchmark'
Submodule 'ext/googletest' (https://github.com/google/googletest.git) registered for path 'ext/ayon-cpp-dev-tools/ext/googletest'
Submodule 'ext/spdlog' (https://github.com/gabime/spdlog.git) registered for path 'ext/ayon-cpp-dev-tools/ext/spdlog'
Cloning into 'E:/Ynput/ayon-cpp-api/ext/ayon-cpp-dev-tools/ext/ayon_automator'...
Cloning into 'E:/Ynput/ayon-cpp-api/ext/ayon-cpp-dev-tools/ext/benchmark'...
Cloning into 'E:/Ynput/ayon-cpp-api/ext/ayon-cpp-dev-tools/ext/googletest'...
Cloning into 'E:/Ynput/ayon-cpp-api/ext/ayon-cpp-dev-tools/ext/spdlog'...
Submodule path 'ext/ayon-cpp-dev-tools/ext/ayon_automator': checked out 'a40e0a040e48079f8d484df0cca4ccdca018a5a4'
Submodule path 'ext/ayon-cpp-dev-tools/ext/benchmark': checked out '144d23cf5fa0b1b9dd138bc56601920d83e350c7'
Submodule path 'ext/ayon-cpp-dev-tools/ext/googletest': checked out '305e5a238b3c8d11266fbafd85520fb6b3184851'
Submodule path 'ext/ayon-cpp-dev-tools/ext/spdlog': checked out '5ebfc927306fd7ce551fa22244be801cf2b9fdd9'
Submodule path 'ext/cpp-httplib': checked out '258992a160e306b6907c74abed448e487b60f74c'

E:\Ynput\ayon-cpp-api>
E:\Ynput\ayon-cpp-api>python AyonBuild.py --setup
------------------------------------ setVar() ------------------------------------
('varName=AYON_CPP_API_ENALBE_GBENCH VarValue=OFF',)
--------------------------------------------------------------------------------

------------------------------------ setVar() ------------------------------------
('varName=AYON_CPP_API_ENALBE_GTEST VarValue=OFF',)
--------------------------------------------------------------------------------

------------------------------------ setVar() ------------------------------------
('varName=JTRACE VarValue=0',)
--------------------------------------------------------------------------------

------------------------------------ setVar() ------------------------------------
('varName=ReleaseType VarValue=Release',)
--------------------------------------------------------------------------------

Deleted Root foulder
Creating Venv: E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\AyonCppApi_BuildVenv
Requirement already satisfied: pip in e:\ynput\ayon-cpp-api\ayoncppapi_cicd\ayoncppapi_buildvenv\lib\site-packages (22.0.4)
Collecting pip
  Using cached pip-25.0.1-py3-none-any.whl (1.8 MB)
Requirement already satisfied: setuptools in e:\ynput\ayon-cpp-api\ayoncppapi_cicd\ayoncppapi_buildvenv\lib\site-packages (58.1.0)
Collecting setuptools
  Using cached setuptools-76.0.0-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.1.0
    Uninstalling setuptools-58.1.0:
      Successfully uninstalled setuptools-58.1.0
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Successfully installed pip-25.0.1 setuptools-76.0.0
Venv Creation Complete, Venv_Path: E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\AyonCppApi_BuildVenv
Requirement already satisfied: pip in e:\ynput\ayon-cpp-api\ayoncppapi_cicd\ayoncppapi_buildvenv\lib\site-packages (25.0.1)
Collecting pytest
  Downloading pytest-8.3.5-py3-none-any.whl.metadata (7.6 kB)
Collecting fastapi==0.109.1
  Using cached fastapi-0.109.1-py3-none-any.whl.metadata (25 kB)
Collecting uvicorn==0.25.0 (from uvicorn[standard]==0.25.0)
  Using cached uvicorn-0.25.0-py3-none-any.whl.metadata (6.4 kB)
Collecting requests
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 (from fastapi==0.109.1)
  Downloading pydantic-2.10.6-py3-none-any.whl.metadata (30 kB)
Collecting starlette<0.36.0,>=0.35.0 (from fastapi==0.109.1)
  Using cached starlette-0.35.1-py3-none-any.whl.metadata (5.8 kB)
Collecting typing-extensions>=4.8.0 (from fastapi==0.109.1)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting click>=7.0 (from uvicorn==0.25.0->uvicorn[standard]==0.25.0)
  Downloading click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
Collecting h11>=0.8 (from uvicorn==0.25.0->uvicorn[standard]==0.25.0)
  Using cached h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Collecting colorama>=0.4 (from uvicorn[standard]==0.25.0)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting httptools>=0.5.0 (from uvicorn[standard]==0.25.0)
  Downloading httptools-0.6.4-cp39-cp39-win_amd64.whl.metadata (3.7 kB)
Collecting python-dotenv>=0.13 (from uvicorn[standard]==0.25.0)
  Using cached python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting pyyaml>=5.1 (from uvicorn[standard]==0.25.0)
  Using cached PyYAML-6.0.2-cp39-cp39-win_amd64.whl.metadata (2.1 kB)
Collecting watchfiles>=0.13 (from uvicorn[standard]==0.25.0)
  Downloading watchfiles-1.0.4-cp39-cp39-win_amd64.whl.metadata (5.0 kB)
Collecting websockets>=10.4 (from uvicorn[standard]==0.25.0)
  Downloading websockets-15.0.1-cp39-cp39-win_amd64.whl.metadata (7.0 kB)
Collecting exceptiongroup>=1.0.0rc8 (from pytest)
  Using cached exceptiongroup-1.2.2-py3-none-any.whl.metadata (6.6 kB)
Collecting iniconfig (from pytest)
  Using cached iniconfig-2.0.0-py3-none-any.whl.metadata (2.6 kB)
Collecting packaging (from pytest)
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pluggy<2,>=1.5 (from pytest)
  Using cached pluggy-1.5.0-py3-none-any.whl.metadata (4.8 kB)
Collecting tomli>=1 (from pytest)
  Using cached tomli-2.2.1-py3-none-any.whl.metadata (10 kB)
Collecting charset-normalizer<4,>=2 (from requests)
  Using cached charset_normalizer-3.4.1-cp39-cp39-win_amd64.whl.metadata (36 kB)
Collecting idna<4,>=2.5 (from requests)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests)
  Using cached urllib3-2.3.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests)
  Using cached certifi-2025.1.31-py3-none-any.whl.metadata (2.5 kB)
Collecting annotated-types>=0.6.0 (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi==0.109.1)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.27.2 (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi==0.109.1)
  Downloading pydantic_core-2.27.2-cp39-cp39-win_amd64.whl.metadata (6.7 kB)
Collecting anyio<5,>=3.4.0 (from starlette<0.36.0,>=0.35.0->fastapi==0.109.1)
  Downloading anyio-4.9.0-py3-none-any.whl.metadata (4.7 kB)
Collecting sniffio>=1.1 (from anyio<5,>=3.4.0->starlette<0.36.0,>=0.35.0->fastapi==0.109.1)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Using cached fastapi-0.109.1-py3-none-any.whl (92 kB)
Using cached uvicorn-0.25.0-py3-none-any.whl (60 kB)
Downloading pytest-8.3.5-py3-none-any.whl (343 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached certifi-2025.1.31-py3-none-any.whl (166 kB)
Using cached charset_normalizer-3.4.1-cp39-cp39-win_amd64.whl (102 kB)
Downloading click-8.1.8-py3-none-any.whl (98 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Downloading httptools-0.6.4-cp39-cp39-win_amd64.whl (89 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached pluggy-1.5.0-py3-none-any.whl (20 kB)
Downloading pydantic-2.10.6-py3-none-any.whl (431 kB)
Downloading pydantic_core-2.27.2-cp39-cp39-win_amd64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 2.2 MB/s eta 0:00:00
Using cached python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Using cached PyYAML-6.0.2-cp39-cp39-win_amd64.whl (162 kB)
Using cached starlette-0.35.1-py3-none-any.whl (71 kB)
Using cached tomli-2.2.1-py3-none-any.whl (14 kB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Using cached urllib3-2.3.0-py3-none-any.whl (128 kB)
Downloading watchfiles-1.0.4-cp39-cp39-win_amd64.whl (284 kB)
Downloading websockets-15.0.1-cp39-cp39-win_amd64.whl (176 kB)
Using cached iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Using cached packaging-24.2-py3-none-any.whl (65 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading anyio-4.9.0-py3-none-any.whl (100 kB)
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Installing collected packages: websockets, urllib3, typing-extensions, tomli, sniffio, pyyaml, python-dotenv, pluggy, packaging, iniconfig, idna, httptools, h11, exceptiongroup, colorama, charset-normalizer, certifi, annotated-types, requests, pytest, pydantic-core, click, anyio, watchfiles, uvicorn, starlette, pydantic, fastapi
Successfully installed annotated-types-0.7.0 anyio-4.9.0 certifi-2025.1.31 charset-normalizer-3.4.1 click-8.1.8 colorama-0.4.6 exceptiongroup-1.2.2 fastapi-0.109.1 h11-0.14.0 httptools-0.6.4 idna-3.10 iniconfig-2.0.0 packaging-24.2 pluggy-1.5.0 pydantic-2.10.6 pydantic-core-2.27.2 pytest-8.3.5 python-dotenv-1.0.1 pyyaml-6.0.2 requests-2.32.3 sniffio-1.3.1 starlette-0.35.1 tomli-2.2.1 typing-extensions-4.12.2 urllib3-2.3.0 uvicorn-0.25.0 watchfiles-1.0.4 websockets-15.0.1
installed all packages
finsihed Setup

E:\Ynput\ayon-cpp-api>python AyonBuild.py --runStageGRP CleanBuildAndTest
------------------------------------ setVar() ------------------------------------
('varName=AYON_CPP_API_ENALBE_GBENCH VarValue=OFF',)
--------------------------------------------------------------------------------

------------------------------------ setVar() ------------------------------------
('varName=AYON_CPP_API_ENALBE_GTEST VarValue=OFF',)
--------------------------------------------------------------------------------

------------------------------------ setVar() ------------------------------------
('varName=JTRACE VarValue=0',)
--------------------------------------------------------------------------------

------------------------------------ setVar() ------------------------------------
('varName=ReleaseType VarValue=Release',)
--------------------------------------------------------------------------------

------------------ Loading Json Variable's File for ths Project ------------------
({'CreationTime': '2025-03-17T12:23:57.091305'},)
--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
Running Stage:  Cleanup
Output file path:  E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\artefacts\Cleanup.txt

##########################################################################################################################################################################FuncName: Remove Build Foulder: E:\Ynput\ayon-cpp-api\build
****************************************************************************************************************************************************************************************************************************************************************************************************************************************************
##########################################################################################################################################################################FuncName: Remove Bin Foulder: E:\Ynput\ayon-cpp-api\bin
****************************************************************************************************************************************************************************************************************************************************************************************************************************************************
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
Running Stage:  SetTestVars
Output file path:  E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\artefacts\SetTestVars.txt

##########################################################################################################################################################################FuncName:
**************************************************************************************************************************************************************************------------------------------------ setVar() ------------------------------------
('varName=AYON_CPP_API_ENALBE_GBENCH VarValue=ON',)
--------------------------------------------------------------------------------

**************************************************************************************************************************************************************************
##########################################################################################################################################################################FuncName:
**************************************************************************************************************************************************************************------------------------------------ setVar() ------------------------------------
('varName=AYON_CPP_API_ENALBE_GTEST VarValue=ON',)
--------------------------------------------------------------------------------

**************************************************************************************************************************************************************************
##########################################################################################################################################################################FuncName:
**************************************************************************************************************************************************************************------------------------------------ setVar() ------------------------------------
('varName=JTRACE VarValue=1',)
--------------------------------------------------------------------------------

**************************************************************************************************************************************************************************
##########################################################################################################################################################################FuncName:
**************************************************************************************************************************************************************************------------------------------------ setVar() ------------------------------------
('varName=ReleaseType VarValue=Release',)
--------------------------------------------------------------------------------

**************************************************************************************************************************************************************************
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
Running Stage:  Build
Output file path:  E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\artefacts\Build.txt

##########################################################################################################################################################################
FuncName: Run Cmake Config Commmand
**************************************************************************************************************************************************************************
CMake output:
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- The CXX compiler identification is MSVC 19.40.33811.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find libdw (missing: LIBDW_LIBRARY LIBDW_INCLUDE_DIR)
-- Could NOT find libbfd (missing: LIBBFD_LIBRARY LIBBFD_INCLUDE_DIR LIBDL_LIBRARY LIBDL_INCLUDE_DIR)
-- Could NOT find libdwarf (missing: LIBDWARF_LIBRARY LIBDWARF_INCLUDE_DIR LIBELF_LIBRARY LIBELF_INCLUDE_DIR LIBDL_LIBRARY LIBDL_INCLUDE_DIR)
-- Found Backward: $<BUILD_INTERFACE:E:/Ynput/ayon-cpp-api/ext/backward-cpp>;$<INSTALL_INTERFACE:include>
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- Using the multi-header code from E:/Ynput/ayon-cpp-api/ext/json/include/
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- Build spdlog: 1.14.1
-- Build type: Release
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.40.33811.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.37.3.windows.1")
-- Google Benchmark version: v1.8.3-73-gbc946b91, normalized to 1.8.3.73
-- Looking for shm_open in rt
-- Looking for shm_open in rt - not found
-- Compiling and running to test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- success
-- Compiling and running to test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Compiling and running to test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- failed to compile
-- Compiling and running to test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Compiling and running to test HAVE_PTHREAD_AFFINITY
-- Performing Test HAVE_PTHREAD_AFFINITY -- failed to compile
-- Performing Test HAVE_CXX_FLAG_WNO_UNUSED_VARIABLE
-- Performing Test HAVE_CXX_FLAG_WNO_UNUSED_VARIABLE - Failed
-- Performing Test BENCHMARK_HAS_O3_FLAG
-- Performing Test BENCHMARK_HAS_O3_FLAG - Failed
-- Performing Test BENCHMARK_HAS_DEPRECATED_DECLARATIONS_FLAG
-- Performing Test BENCHMARK_HAS_DEPRECATED_DECLARATIONS_FLAG - Failed
-- Configuring done (9.7s)
-- Generating done (0.3s)
-- Build files have been written to: E:/Ynput/ayon-cpp-api/build

**************************************************************************************************************************************************************************

##########################################################################################################################################################################
FuncName: Run Cmake Build Command
**************************************************************************************************************************************************************************
CMake output:
MSBuild version 17.10.4+10fbfbf2e for .NET Framework

  1>Checking Build System
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/backward-cpp/CMakeLists.txt
  backward.cpp
E:\Ynput\ayon-cpp-api\ext\backward-cpp\backward.hpp(3825,37): warning C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [E:\Ynput\ayon-cpp-api\build\ext\backward-cpp\backward_object.vcxproj]
  backward_object.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\backward-cpp\backward_object.dir\Release\backward_object.lib
  Building Custom Rule E:/Ynput/ayon-cpp-api/src/AyonCppApi/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/googletest/googletest/CMakeLists.txt
  cmake_pch.cxx
  gtest-all.cc
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/backward-cpp/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/src/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/googletest/googlemock/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/googletest/googlemock/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/ayon-cpp-dev-tools/ext/spdlog/CMakeLists.txt
  backward.cpp
  benchmark.cc
  gtest-all.cc
  gtest-all.cc
  spdlog.cpp
  stdout_sinks.cpp
  color_sinks.cpp
  file_sinks.cpp
  async.cpp
  cfg.cpp
  bundled_fmtlib_format.cpp
E:\Ynput\ayon-cpp-api\ext\backward-cpp\backward.hpp(3825,37): warning C4996: 'getenv': This function or variable may be unsafe. Consider using _dupenv_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. [E:\Ynput\ayon-cpp-api\build\ext\backward-cpp\backward.vcxproj]
  backward.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\backward-cpp\Release\backward.lib
  benchmark_api_internal.cc
  gmock-all.cc
  gmock-all.cc
  spdlog.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\ayon-cpp-dev-tools\ext\spdlog\Release\spdlog.lib
  AyonCppApi.cpp
  benchmark_name.cc
E:\Ynput\ayon-cpp-api\ext\ayon-cpp-dev-tools\src\lib\ynput\lib\logging\AyonLogger.hpp(171,46): error C2672: 'spdlog::basic_logger_mt': no matching overloaded function found [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]
  benchmark_register.cc
  gtest.vcxproj -> E:\Ynput\ayon-cpp-api\build\lib\Release\gtest.lib
E:\Ynput\ayon-cpp-api\src\AyonCppApi\Instrumentor.h(117,31): warning C4267: 'initializing': conversion from 'size_t' to 'uint32_t', possible loss of data [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]     
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/googletest/googletest/CMakeLists.txt
E:\Ynput\ayon-cpp-api\src\AyonCppApi\AyonCppApi.cpp(74,44): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]
  Generating Code...
  gtest_main.cc
  gmock_main.cc
E:\Ynput\ayon-cpp-api\src\AyonCppApi\AyonCppApi.cpp(415,27): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj] 
E:\Ynput\ayon-cpp-api\src\AyonCppApi\AyonCppApi.cpp(441,25): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]
E:\Ynput\ayon-cpp-api\src\AyonCppApi\AyonCppApi.cpp(454,30): warning C4244: '=': conversion from 'double' to 'int', possible loss of data [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]
E:\Ynput\ayon-cpp-api\src\AyonCppApi\AyonCppApi.cpp(460,38): warning C4244: '=': conversion from 'double' to 'int', possible loss of data [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]
E:\Ynput\ayon-cpp-api\src\AyonCppApi\AyonCppApi.cpp(461,41): warning C4244: '=': conversion from 'double' to 'int', possible loss of data [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]
E:\Ynput\ayon-cpp-api\src\AyonCppApi\AyonCppApi.cpp(470,41): warning C4244: '=': conversion from 'double' to 'int', possible loss of data [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]
E:\Ynput\ayon-cpp-api\src\AyonCppApi\AyonCppApi.cpp(478,37): warning C4244: '=': conversion from 'double' to 'int', possible loss of data [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]
  benchmark_runner.cc
  gtest_main.vcxproj -> E:\Ynput\ayon-cpp-api\build\lib\Release\gtest_main.lib
  Generating Code...
  gmock.vcxproj -> E:\Ynput\ayon-cpp-api\build\lib\Release\gmock.lib
  check.cc
  colorprint.cc
  gmock_main.vcxproj -> E:\Ynput\ayon-cpp-api\build\lib\Release\gmock_main.lib
  commandlineflags.cc
  complexity.cc
  console_reporter.cc
  counter.cc
  csv_reporter.cc
  json_reporter.cc
  perf_counters.cc
  reporter.cc
  statistics.cc
  string_util.cc
  sysinfo.cc
  timers.cc
  Generating Code...
  benchmark.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\src\Release\benchmark.lib
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/src/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  output_test_helper.cc
  args_product_test.cc
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  benchmark_setup_teardown_test.cc
  options_test.cc
  min_time_parse_gtest.cc
  donotoptimize_test.cc
  spec_arg_test.cc
  benchmark_min_time_flag_iters_test.cc
  benchmark_main.cc
  benchmark_gtest.cc
  benchmark_name_gtest.cc
  skip_with_error_test.cc
  benchmark_min_time_flag_time_test.cc
  filter_test.cc
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  basic_test.cc
  benchmark_random_interleaving_gtest.cc
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  perf_counters_gtest.cc
  commandlineflags_gtest.cc
  time_unit_gtest.cc
  register_benchmark_test.cc
  statistics_gtest.cc
  map_test.cc
  multiple_ranges_test.cc
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  fixture_test.cc
  diagnostics_test.cc
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  string_util_gtest.cc
  donotoptimize_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\donotoptimize_test.exe
  benchmark_test.cc
  benchmark_main.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\src\Release\benchmark_main.lib
  benchmark_min_time_flag_time_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\benchmark_min_time_flag_time_test.exe
  options_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\options_test.exe
  spec_arg_verbosity_test.cc
  benchmark_min_time_flag_iters_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\benchmark_min_time_flag_iters_test.exe
  filter_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\filter_test.exe
  basic_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\basic_test.exe
  map_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\map_test.exe
  spec_arg_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\spec_arg_test.exe
  args_product_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\args_product_test.exe
  benchmark_setup_teardown_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\benchmark_setup_teardown_test.exe
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  link_main_test.cc
  fixture_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\fixture_test.exe
  multiple_ranges_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\multiple_ranges_test.exe
  benchmark_name_gtest.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\benchmark_name_gtest.exe
  time_unit_gtest.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\time_unit_gtest.exe
  statistics_gtest.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\statistics_gtest.exe
  skip_with_error_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\skip_with_error_test.exe
  register_benchmark_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\register_benchmark_test.exe
  min_time_parse_gtest.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\min_time_parse_gtest.exe
  spec_arg_verbosity_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\spec_arg_verbosity_test.exe
  link_main_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\link_main_test.exe
  diagnostics_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\diagnostics_test.exe
  benchmark_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\benchmark_test.exe
  output_test_helper.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\output_test_helper.lib
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  benchmark_random_interleaving_gtest.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\benchmark_random_interleaving_gtest.exe
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  internal_threading_test.cc
  templated_fixture_test.cc
  perf_counters_test.cc
  reporter_output_test.cc
  repetitions_test.cc
  user_counters_thousands_test.cc
  display_aggregates_only_test.cc
  user_counters_test.cc
  commandlineflags_gtest.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\commandlineflags_gtest.exe
  report_aggregates_only_test.cc
  perf_counters_gtest.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\perf_counters_gtest.exe
  complexity_test.cc
  user_counters_tabular_test.cc
  Building Custom Rule E:/Ynput/ayon-cpp-api/ext/benchmark/test/CMakeLists.txt
  memory_manager_test.cc
  templated_fixture_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\templated_fixture_test.exe
  benchmark_gtest.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\benchmark_gtest.exe
  string_util_gtest.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\string_util_gtest.exe
  display_aggregates_only_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\display_aggregates_only_test.exe
  report_aggregates_only_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\report_aggregates_only_test.exe
  perf_counters_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\perf_counters_test.exe
  internal_threading_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\internal_threading_test.exe
  repetitions_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\repetitions_test.exe
  memory_manager_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\memory_manager_test.exe
  user_counters_thousands_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\user_counters_thousands_test.exe
  complexity_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\complexity_test.exe
  user_counters_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\user_counters_test.exe
  reporter_output_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\reporter_output_test.exe
  user_counters_tabular_test.vcxproj -> E:\Ynput\ayon-cpp-api\build\ext\benchmark\test\Release\user_counters_tabular_test.exe

******************************************************************************************************************************************************************************************************************************
##############################################################################################################################################################################################################################FuncName: Run Cmake Install Command
******************************************************************************************************************************************************************************************************************************CMake output:
-- Install configuration: "Release"
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/backward.hpp
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/cmake/backward/BackwardConfig.cmake
-- Up-to-date: E:/Ynput/ayon-cpp-api/bin/include
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock/gmock-actions.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock/gmock-cardinalities.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock/gmock-function-mocker.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock/gmock-matchers.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock/gmock-more-actions.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock/gmock-more-matchers.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock/gmock-nice-strict.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock/gmock-spec-builders.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock/gmock.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock/internal
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock/internal/custom
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock/internal/custom/gmock-generated-actions.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock/internal/custom/gmock-matchers.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock/internal/custom/gmock-port.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock/internal/custom/README.md
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock/internal/gmock-internal-utils.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock/internal/gmock-port.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gmock/internal/gmock-pp.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/gmock.lib
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/gmock_main.lib
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/pkgconfig/gmock.pc
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/pkgconfig/gmock_main.pc
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/cmake/GTest/GTestTargets.cmake
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/cmake/GTest/GTestTargets-release.cmake
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/cmake/GTest/GTestConfigVersion.cmake
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/cmake/GTest/GTestConfig.cmake
-- Up-to-date: E:/Ynput/ayon-cpp-api/bin/include
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/gtest-assertion-result.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/gtest-death-test.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/gtest-matchers.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/gtest-message.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/gtest-param-test.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/gtest-printers.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/gtest-spi.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/gtest-test-part.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/gtest-typed-test.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/gtest.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/gtest_pred_impl.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/gtest_prod.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/internal
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/internal/custom
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/internal/custom/gtest-port.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/internal/custom/gtest-printers.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/internal/custom/gtest.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/internal/custom/README.md
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/internal/gtest-death-test-internal.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/internal/gtest-filepath.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/internal/gtest-internal.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/internal/gtest-param-util.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/internal/gtest-port-arch.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/internal/gtest-port.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/internal/gtest-string.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/gtest/internal/gtest-type-util.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/gtest.lib
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/gtest_main.lib
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/pkgconfig/gtest.pc
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/pkgconfig/gtest_main.pc
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/benchmark.lib
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/benchmark_main.lib
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/benchmark
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/benchmark/benchmark.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/include/benchmark/export.h
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/cmake/benchmark/benchmarkConfig.cmake
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/cmake/benchmark/benchmarkConfigVersion.cmake
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/pkgconfig/benchmark.pc
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/pkgconfig/benchmark_main.pc
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/cmake/benchmark/benchmarkTargets.cmake
-- Installing: E:/Ynput/ayon-cpp-api/bin/lib/cmake/benchmark/benchmarkTargets-release.cmake
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark/AssemblyTests.md
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark/assets
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark/assets/images
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark/assets/images/icon.png
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark/assets/images/icon.xcf
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark/assets/images/icon_black.png
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark/assets/images/icon_black.xcf
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark/dependencies.md
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark/index.md
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark/perf_counters.md
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark/platform_specific_build_instructions.md
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark/python_bindings.md
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark/random_interleaving.md
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark/reducing_variance.md
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark/releasing.md
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark/tools.md
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark/user_guide.md
-- Installing: E:/Ynput/ayon-cpp-api/bin/share/doc/benchmark/_config.yml

CMake errors:
Error at build/test/cmake_install.cmake:55 (file):
  file INSTALL cannot find
  "E:/Ynput/ayon-cpp-api/build/test/Release/AyonCppApiGtestMain.exe": File
  exists.
Call Stack (most recent call first):
  build/cmake_install.cmake:57 (include)

******************************************************************************************************************************************************************************************************************************
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
Running Stage:  SetupTestServer
Output file path:  E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\artefacts\SetupTestServer.txt

----------------------------------- __exit__() -----------------------------------
("Project ExitLog: type: <class 'ImportError'>, val: cannot import name "
 "'TypeIs' from 'typing_extensions' (C:\\Users\\Mustafa "
 'Taher\\AppData\\Roaming\\Python\\Python39\\site-packages\\typing_extensions.py), '
 'traceback: <traceback object at 0x000002331192AF40>',)
--------------------------------------------------------------------------------

Traceback (most recent call last):
  File "E:\Ynput\ayon-cpp-api\AyonBuild.py", line 267, in <module>
    PRJ.make_project_cli_available()
  File "E:\Ynput\ayon-cpp-api\ayon_automator\AyonCiCd\Project.py", line 353, in make_project_cli_available
    self.runStageGRP(stage_grp_name)
  File "E:\Ynput\ayon-cpp-api\ayon_automator\AyonCiCd\Project.py", line 502, in runStageGRP
    self._call_stage_execution(stage)
  File "E:\Ynput\ayon-cpp-api\ayon_automator\AyonCiCd\Project.py", line 460, in _call_stage_execution
    output = Stage.exec_stage(self)
  File "E:\Ynput\ayon-cpp-api\ayon_automator\AyonCiCd\Project.py", line 672, in exec_stage
    func.run()
  File "E:\Ynput\ayon-cpp-api\ayon_automator\AyonCiCd\Project.py", line 73, in run
    return self.func(*args, **kwargs)
  File "E:\Ynput\ayon-cpp-api\AyonBuild.py", line 154, in startTestServer
    from test import TestServer
  File "E:\Ynput\ayon-cpp-api\test\TestServer.py", line 125, in <module>
    from fastapi import FastAPI, HTTPException
  File "E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\AyonCppApi_BuildVenv\Lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\AyonCppApi_BuildVenv\Lib\site-packages\fastapi\applications.py", line 16, in <module>
    from fastapi import routing
  File "E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\AyonCppApi_BuildVenv\Lib\site-packages\fastapi\routing.py", line 22, in <module>
    from fastapi import params
  File "E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\AyonCppApi_BuildVenv\Lib\site-packages\fastapi\params.py", line 5, in <module>
    from fastapi.openapi.models import Example
  File "E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\AyonCppApi_BuildVenv\Lib\site-packages\fastapi\openapi\models.py", line 4, in <module>
    from fastapi._compat import (
  File "E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\AyonCppApi_BuildVenv\Lib\site-packages\fastapi\_compat.py", line 20, in <module>
    from fastapi.exceptions import RequestErrorModel
  File "E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\AyonCppApi_BuildVenv\Lib\site-packages\fastapi\exceptions.py", line 3, in <module>
    from pydantic import BaseModel, create_model
  File "E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\AyonCppApi_BuildVenv\Lib\site-packages\pydantic\__init__.py", line 421, in __getattr__
    module = import_module(module_name, package=package)
  File "C:\.pyenv\pyenv-win\versions\3.9.13\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\AyonCppApi_BuildVenv\Lib\site-packages\pydantic\main.py", line 34, in <module>
    from ._internal import (
  File "E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\AyonCppApi_BuildVenv\Lib\site-packages\pydantic\_internal\_decorators.py", line 16, in <module>
    from ._core_utils import get_type_ref
  File "E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\AyonCppApi_BuildVenv\Lib\site-packages\pydantic\_internal\_core_utils.py", line 12, in <module>
    from . import _repr
  File "E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\AyonCppApi_BuildVenv\Lib\site-packages\pydantic\_internal\_repr.py", line 11, in <module>
    from . import _typing_extra
  File "E:\Ynput\ayon-cpp-api\AyonCppApi_cicd\AyonCppApi_BuildVenv\Lib\site-packages\pydantic\_internal\_typing_extra.py", line 15, in <module>
    from typing_extensions import TypeIs, deprecated, get_args, get_origin
ImportError: cannot import name 'TypeIs' from 'typing_extensions' (C:\Users\Mustafa Taher\AppData\Roaming\Python\Python39\site-packages\typing_extensions.py)
----------------------------------- __del__() -----------------------------------
("Finished Execution with code:1, {'Cmake': ['Error at "
 'build/test/cmake_install.cmake:55 (file):\\n  file INSTALL cannot find\\n  '
 '"E:/Ynput/ayon-cpp-api/build/test/Release/AyonCppApiGtestMain.exe": File\\n  '
 'exists.\\nCall Stack (most recent call first):\\n  '
 "build/cmake_install.cmake:57 (include)']}",)
--------------------------------------------------------------------------------

Exception ignored in: <function Project.__del__ at 0x000002330F8D0700>
Traceback (most recent call last):
  File "E:\Ynput\ayon-cpp-api\ayon_automator\AyonCiCd\Project.py", line 193, in __del__
SystemExit: 1

E:\Ynput\ayon-cpp-api>"E:/Ynput/ayon-cpp-api/build/test/Release/"
'"E:/Ynput/ayon-cpp-api/build/test/Release/"' is not recognized as an internal or external command,
operable program or batch file.

E:\Ynput\ayon-cpp-api>
```

</details>

**Comment by tadeas-hejnic** [comment]
The reported error: `E:\Ynput\ayon-cpp-api\ext\ayon-cpp-dev-tools\src\lib\ynput\lib\logging\AyonLogger.hpp(171,46): error C2672: 'spdlog::basic_logger_mt': no matching overloaded function found [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]
  benchmark_register.cc` is fixed in this [PR ](https://github.com/ynput/ayon-cpp-dev-tools/pull/8) - waiting for review/merge.

**Review by MustafaJafar — COMMENTED** [review]
[I hope this is not related to my dev setup, please let me know if this is related to my dev setup.]
I was not able to run the test server. But any ways, I followed another way to test your PR by following my example [here](https://ayon.ynput.io/docs/dev_api_cpp), (clean build the cpp api tools, include it in a code, build and run the code.)

running the following command was successful
```
python AyonBuild.py --runStageGRP CleanBuild
```

On build the example, I got this error
```
6>E:\Ynput\tests\cpp_api_expriment\ext\ayon-cpp-api\src\AyonCppApi\AyonCppApi.h(12,10): error C1083: Cannot open include file: 'lib/ynput/lib/logging/AyonLogger.hpp': No such file or directory
```

---
Additionally, I've got a lot of warnings. 
<details><summary>Here's the full log of building my example</summary>

```
E:\Ynput\tests\cpp_api_expriment>devenv build/main.sln /Build 

Microsoft Visual Studio 2022 Version 17.10.3.
Copyright (C) Microsoft Corp. All rights reserved.
Build started at 2:32 PM...
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>1>Checking Build System
2>------ Build started: Project: spdlog, Configuration: Debug x64 ------
3>------ Build started: Project: backward_object, Configuration: Debug x64 ------
4>------ Build started: Project: backward, Configuration: Debug x64 ------
5>------ Build started: Project: AyonCppApi, Configuration: Debug x64 ------
2>Building Custom Rule E:/Ynput/tests/cpp_api_expriment/ext/ayon-cpp-api/ext/ayon-cpp-dev-tools/ext/spdlog/CMakeLists.txt
3>Building Custom Rule E:/Ynput/tests/cpp_api_expriment/ext/ayon-cpp-api/ext/backward-cpp/CMakeLists.txt
3>backward.cpp
2>spdlog.cpp
4>Building Custom Rule E:/Ynput/tests/cpp_api_expriment/ext/ayon-cpp-api/ext/backward-cpp/CMakeLists.txt
2>stdout_sinks.cpp
2>color_sinks.cpp
2>file_sinks.cpp
2>async.cpp
2>cfg.cpp
2>bundled_fmtlib_format.cpp
5>Building Custom Rule E:/Ynput/tests/cpp_api_expriment/ext/ayon-cpp-api/src/AyonCppApi/CMakeLists.txt
4>backward.cpp
5>cmake_pch.cxx
3>backward_object.vcxproj -> E:\Ynput\tests\cpp_api_expriment\build\ext\ayon-cpp-api\ext\backward-cpp\backward_object.dir\Debug\backward_object.lib
4>backward.vcxproj -> E:\Ynput\tests\cpp_api_expriment\build\ext\ayon-cpp-api\ext\backward-cpp\Debug\backward.lib
2>spdlog.vcxproj -> E:\Ynput\tests\cpp_api_expriment\build\ext\ayon-cpp-api\ext\ayon-cpp-dev-tools\ext\spdlog\Debug\spdlogd.lib
5>AyonCppApi.cpp
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning. 
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996:             T=fmt::v9::detail::bigint::bigit       
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996: 'stdext::checked_array_iterator<T *>::_Prevent_inheriting_unwrap': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed 
in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996:             T=fmt::v9::detail::bigint::bigit       
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996:             T=fmt::v9::detail::bigint::bigit
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996: 'stdext::checked_array_iterator<T *>::iterator_category': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996:             T=fmt::v9::detail::bigint::bigit
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996:             T=fmt::v9::detail::bigint::bigit
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996: 'stdext::checked_array_iterator<T *>::value_type': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to 
suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996:             T=fmt::v9::detail::bigint::bigit
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996:             T=fmt::v9::detail::bigint::bigit
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996: 'stdext::checked_array_iterator<T *>::difference_type': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed 
in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996:             T=fmt::v9::detail::bigint::bigit
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996:             T=fmt::v9::detail::bigint::bigit
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996: 'stdext::checked_array_iterator<T *>::pointer': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996:             T=fmt::v9::detail::bigint::bigit
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996:             T=fmt::v9::detail::bigint::bigit
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996: 'stdext::checked_array_iterator<T *>::reference': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996:             T=fmt::v9::detail::bigint::bigit
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996: 'stdext::checked_array_iterator<T *>::_Verify_offset': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996:             T=fmt::v9::detail::bigint::bigit       
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996: 'stdext::checked_array_iterator<T *>::_Unwrapped': 
warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996:             T=fmt::v9::detail::bigint::bigit       
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning. 
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996:             T=char
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996: 'stdext::checked_array_iterator<T *>::_Prevent_inheriting_unwrap': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed 
in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996:             T=char
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996:             T=char
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996: 'stdext::checked_array_iterator<T *>::iterator_category': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996:             T=char
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996:             T=char
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996: 'stdext::checked_array_iterator<T *>::value_type': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to 
suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996:             T=char
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996:             T=char
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996: 'stdext::checked_array_iterator<T *>::difference_type': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed 
in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996:             T=char
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996:             T=char
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996: 'stdext::checked_array_iterator<T *>::pointer': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996:             T=char
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996:             T=char
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996: 'stdext::checked_array_iterator<T *>::reference': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996:             T=char
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996: 'stdext::checked_array_iterator<T *>::_Verify_offset': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996:             T=char
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996: 'stdext::checked_array_iterator<T *>::_Unwrapped': 
warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996:             T=char
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning. 
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996:             T=wchar_t
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996: 'stdext::checked_array_iterator<T *>::_Prevent_inheriting_unwrap': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed 
in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996:             T=wchar_t
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996:             T=wchar_t
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996: 'stdext::checked_array_iterator<T *>::iterator_category': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996:             T=wchar_t
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996:             T=wchar_t
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996: 'stdext::checked_array_iterator<T *>::value_type': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to 
suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996:             T=wchar_t
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996:             T=wchar_t
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996: 'stdext::checked_array_iterator<T *>::difference_type': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed 
in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996:             T=wchar_t
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996:             T=wchar_t
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996: 'stdext::checked_array_iterator<T *>::pointer': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996:             T=wchar_t
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996:             T=wchar_t
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996: 'stdext::checked_array_iterator<T *>::reference': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996:             T=wchar_t
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996: 'stdext::checked_array_iterator<T *>::_Verify_offset': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996:             T=wchar_t
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996: 'stdext::checked_array_iterator<T *>::_Unwrapped': 
warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996:             T=wchar_t
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1406,13): warning C4996: 'stdext::checked_array_iterator<T *>::_Seek_to': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1406,13): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1406,13): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1406,13): warning C4996:             T=fmt::v9::detail::bigint::bigit       
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1406,13): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1406,13): warning C4996: 'stdext::checked_array_iterator<T *>::_Seek_to': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1406,13): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1406,13): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1406,13): warning C4996:             T=char
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1406,13): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning. 
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996:             T=int
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996: 'stdext::checked_array_iterator<T *>::_Prevent_inheriting_unwrap': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed 
in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996:             T=int
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1266,22): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996:             T=int
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996: 'stdext::checked_array_iterator<T *>::iterator_category': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996:             T=int
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(490,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996:             T=int
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996: 'stdext::checked_array_iterator<T *>::value_type': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to 
suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996:             T=int
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(491,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996:             T=int
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996: 'stdext::checked_array_iterator<T *>::difference_type': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed 
in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996:             T=int
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(492,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996:             T=int
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996: 'stdext::checked_array_iterator<T *>::pointer': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996:             T=int
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(493,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996: 'stdext::checked_array_iterator<T *>': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996:             T=int
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,40): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996: 'stdext::checked_array_iterator<T *>::reference': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996:             T=int
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\__msvc_iter_core.hpp(494,31): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996: 'stdext::checked_array_iterator<T *>::_Verify_offset': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996:             T=int
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1384,13): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996: 'stdext::checked_array_iterator<T *>::_Unwrapped': 
warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996:             T=int
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1385,42): warning C4996:         ]
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1406,13): warning C4996: 'stdext::checked_array_iterator<T *>::_Seek_to': warning STL4043: stdext::checked_array_iterator, stdext::unchecked_array_iterator, and related factory functions are non-Standard extensions and will be removed in the future. std::span (since C++20) and gsl::span can be used instead. You can define _SILENCE_STDEXT_ARR_ITERS_DEPRECATION_WARNING or _SILENCE_ALL_MS_EXT_DEPRECATION_WARNINGS to suppress this warning.
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1406,13): warning C4996:         with
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1406,13): warning C4996:         [
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1406,13): warning C4996:             T=int
5>C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\xutility(1406,13): warning C4996:         ]
5>AyonCppApi.vcxproj -> E:\Ynput\tests\cpp_api_expriment\build\ext\ayon-cpp-api\src\AyonCppApi\Debug\AyonCppApi.lib
5>Done building project "AyonCppApi.vcxproj".
6>------ Build started: Project: main, Configuration: Debug x64 ------
6>Building Custom Rule E:/Ynput/tests/cpp_api_expriment/CMakeLists.txt
6>main.cpp
6>E:\Ynput\tests\cpp_api_expriment\ext\ayon-cpp-api\src\AyonCppApi\AyonCppApi.h(12,10): error C1083: Cannot open include file: 'lib/ynput/lib/logging/AyonLogger.hpp': No such file or directory
6>Done building project "main.vcxproj" -- FAILED.
7>------ Build started: Project: ALL_BUILD, Configuration: Debug x64 ------
7>Building Custom Rule E:/Ynput/tests/cpp_api_expriment/CMakeLists.txt
8>------ Skipped Build: Project: PACKAGE, Configuration: Debug x64 ------
8>Project not selected to build for this solution configuration
9>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
9>Project not selected to build for this solution configuration
========== Build: 6 succeeded, 1 failed, 0 up-to-date, 2 skipped ==========
========== Build completed at 2:32 PM and took 06.405 seconds ==========
```

</details>

**Comment by tadeas-hejnic** [comment]
Now should be fixed all your reported errors. The warnings when building CLI cmake with Debug argument are still there and probably can't be really fixed as it is Microsoft issue - https://github.com/microsoft/cpprestsdk/issues/1768.

File: src/AyonCppApi/AyonCppApi.cpp [hunk 1]
```diff
@@ -78,11 +209,17 @@ std::unordered_map<std::string, std::string>*
 AyonApi::getSiteRoots() {
     m_Log->info(m_Log->key("AyonApi"), "AyonApi::getSiteRoots()");
     if (m_siteRoots.size() < 1) {
-        httplib::Headers headers = {{"X-ayon-site-id", m_siteId}};
         nlohmann::json response
-            = GET(std::make_shared<std::string>("/api/projects/" + m_ayonProjectName + "/siteRoots"),
-                  std::make_shared<httplib::Headers>(headers), 200);
-        m_siteRoots = response;
+            = GET(std::make_shared<std::string>("/api/projects/" + m_ayonProjectName + "/siteRoots?platform=linux"),
+                  std::make_shared<httplib::Headers>(m_headers), 200);
```
Comment (Lypsolon) [inline src/AyonCppApi/AyonCppApi.cpp]:
```suggestion
    #ifdef _WIN32
       response = GET(std::make_shared<std::string>("/api/projects/" + m_ayonProjectName + "/siteRoots?platform=windows"), std::make_shared<httplib::Headers>(m_headers), 200);
    #else
       response = GET(std::make_shared<std::string>("/api/projects/" + m_ayonProjectName + "/siteRoots?platform=linux"), std::make_shared<httplib::Headers>(m_headers), 200);
    #endif

```



would be best to set the windows Linux etc options at compile time 
cheap solution via ifdef ? like the ones you did atop ? 

https://docs.ayon.dev/api#tag/Projects/operation/get_project_site_roots

**Comment by MustafaJafar** [comment]
Currently, on my side (windows). I'm only building the package. 
Steps I'm following: 
```
git submodule update --init --recursive
python AyonBuild.py --setup
python AyonBuild.py --runStageGRP CleanBuild
```
The INSTALL wasn't able to find `./ayon-cpp-api/build/src/AyonCppApi/Release/AyonCppApi.lib`
here's the generated log.
[Build.txt](https://github.com/user-attachments/files/19630992/Build.txt)

I believe this is the most important part in the log
```
E:\Ynput\ayon-cpp-api\ext\ayon-cpp-dev-tools\src\lib\ynput\lib\logging\AyonLogger.hpp(171,46): error C2672: 'spdlog::basic_logger_mt': no matching overloaded function found [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]
E:\Ynput\ayon-cpp-api\src\AyonCppApi\AyonCppApi.cpp(79,44): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]
E:\Ynput\ayon-cpp-api\src\AyonCppApi\AyonCppApi.cpp(425,27): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]
E:\Ynput\ayon-cpp-api\src\AyonCppApi\AyonCppApi.cpp(451,25): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]
E:\Ynput\ayon-cpp-api\src\AyonCppApi\AyonCppApi.cpp(464,30): warning C4244: '=': conversion from 'double' to 'int', possible loss of data [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]
E:\Ynput\ayon-cpp-api\src\AyonCppApi\AyonCppApi.cpp(470,38): warning C4244: '=': conversion from 'double' to 'int', possible loss of data [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]
E:\Ynput\ayon-cpp-api\src\AyonCppApi\AyonCppApi.cpp(471,41): warning C4244: '=': conversion from 'double' to 'int', possible loss of data [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]
E:\Ynput\ayon-cpp-api\src\AyonCppApi\AyonCppApi.cpp(480,41): warning C4244: '=': conversion from 'double' to 'int', possible loss of data [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]
E:\Ynput\ayon-cpp-api\src\AyonCppApi\AyonCppApi.cpp(488,37): warning C4244: '=': conversion from 'double' to 'int', possible loss of data [E:\Ynput\ayon-cpp-api\build\src\AyonCppApi\AyonCppApi.vcxproj]
```

**Comment by tadeas-hejnic** [comment]
Pushed the change of git pointer to the commit that fixes the error

**Review by MustafaJafar — COMMENTED** [review]
I was able to build the ayon-cpp-api lib as well as my test code without issues.

```cpp
// AYON CPP API Test
#include "AyonCppApi.h"

int main (){
    AyonApi con = AyonApi(
        "log/file/log.txt",
        "your_api_key",
        "https://your.server",
        "project_name",
        "testSiteId"
    );
    return 0;
}
```
---
Maybe it's irrelevent to this PR but the generate log file.
- it was saved as `,josn` ignoring my `.txt` 
- the json output was missing the enclosing `[ ]` and separation commas.

output: 
[log.json](https://github.com/user-attachments/files/19632479/log.json)

File: src/AyonCppApi/AyonCppApi.cpp [hunk 2]
```diff
@@ -78,11 +211,17 @@ std::unordered_map<std::string, std::string>*
 AyonApi::getSiteRoots() {
     m_Log->info(m_Log->key("AyonApi"), "AyonApi::getSiteRoots()");
     if (m_siteRoots.size() < 1) {
-        httplib::Headers headers = {{"X-ayon-site-id", m_siteId}};
         nlohmann::json response
-            = GET(std::make_shared<std::string>("/api/projects/" + m_ayonProjectName + "/siteRoots"),
-                  std::make_shared<httplib::Headers>(headers), 200);
-        m_siteRoots = response;
+            = GET(std::make_shared<std::string>("/api/projects/" + m_ayonProjectName + "/siteRoots?platform=linux"),
```
Comment (MustafaJafar) [inline src/AyonCppApi/AyonCppApi.cpp]: does it mean that I have to be on linux?
Also, do we need this fallback since the site id is not an optional argument so we can always rely on it?

Comment (tadeas-hejnic) [reply src/AyonCppApi/AyonCppApi.cpp]: Yeah, this shouldn’t be hardcoded - the platform should be set based on the actual environment. 
It has to be done this way - otherwise the connection to https servers doesn't work.

Comment (MustafaJafar) [reply src/AyonCppApi/AyonCppApi.cpp]: Fixed https://github.com/ynput/ayon-cpp-api/pull/35/commits/871ed1b14408b09776f04c7f99b3176cfcd6c2f7

**Review by MustafaJafar — APPROVED** [review]
It works on my side.
was able to do a successful build and my exampl cpp was build and run without issues.

For future reference, here's my test cpp code: 
```cpp
// AYON CPP API Test
#include "AyonCppApi.h"

int main (){
    AyonApi con = AyonApi(
        "log/file/log.txt",
        "your_api_key", // This is a Bearer token not AYON_API_KEY
        "https://your.server", // with No trailing forward slash /
        "project_name",
        "testSiteId"
    );
    return 0;
}
```

File: src/AyonCppApi/AyonCppApi.cpp [hunk 3]
```diff
@@ -32,57 +32,202 @@
...
+                std::string certFile = opensslDir + "\\cert.pem";
+                #else
+                std::string certFile = opensslDir + "/cert.pem";
+                #endif
+
+                if (std::filesystem::exists(certFile)) {
+                    m_Log->info("Using cert based on SSLEAY_DIR.");
+                    m_AyonServer->set_ca_cert_path(certFile.c_str()); 
+                } else {
+                    const char* envCertFile = getenv("SSL_CERT_FILE");
```
Comment (Lypsolon) [inline src/AyonCppApi/AyonCppApi.cpp]: I believe the environment variable should be the first option making use of an early return or just avoiding the other code. 

I would argue that if you define a cert file explicitly, it should be the one to use if possible. 
Maybe it should even be possible to enforce only to use the one provided there so that if a studio defines one explicitly, they can enforce it. 

PS;: not saying the fallback idea is bad or anything still a great idea.

File: src/AyonCppApi/AyonCppApi.cpp [hunk 4]
```diff
@@ -32,57 +32,202 @@
...
     m_Log->info(m_Log->key("AyonApi"), "Init AyonServer httplib::Client");
     m_AyonServer = std::make_unique<httplib::Client>(m_serverUrl);
-    m_AyonServer->set_bearer_token_auth(m_authKey);
+
+    if (isSSL()) {
+        m_headers = {
+            {"X-Api-Key", m_authKey},
+        };
+
+        try {
```
Comment (Lypsolon) [inline src/AyonCppApi/AyonCppApi.cpp]: I believe it might be best to have everything in the try in a separate function. Would make expanding the business logic a bit simpler. 
You can just make it an inlined function if you are afraid of performance or any behavior changes.

File: src/AyonCppApi/AyonCppApi.cpp [hunk 5]
```diff
@@ -32,57 +32,202 @@
...
     m_Log->info(m_Log->key("AyonApi"), "AyonApi::getSiteRoots()");
-    if (m_siteRoots.size() < 1) {
-        httplib::Headers headers = {{"X-ayon-site-id", m_siteId}};
-        nlohmann::json response
-            = GET(std::make_shared<std::string>("/api/projects/" + m_ayonProjectName + "/siteRoots"),
-                  std::make_shared<httplib::Headers>(headers), 200);
-        m_siteRoots = response;
+        if (m_siteRoots.size() < 1) {
+            std::string platform;
+            #ifdef _WIN32
```
Comment (Lypsolon) [inline src/AyonCppApi/AyonCppApi.cpp:216]: Might be best to make this a macro and let the preprocessing place it in the right places. This would allow the compiler to collapse all the string stuff into a singe object. 
You could also constexpression the thing. 

Also if you make it a macro you can just use it anywhere.

File: src/AyonCppApi/AyonCppApi.cpp [hunk 6]
```diff
@@ -587,3 +738,8 @@ AyonApi::logPointer() {
     m_Log->info(m_Log->key("AyonApi"), "AyonApi::logPointer()");
     return m_Log;
 };
+
+bool
+AyonApi::isSSL() const {
+    return m_serverUrl.rfind("https://", 0) == 0;
```
Comment (Lypsolon) [inline src/AyonCppApi/AyonCppApi.cpp:748]: Doing this as a compare of a substring might be faster. 
But rfind is very fast so you might end up with +- 0
Just FYI

File: src/AyonCppApi/AyonCppApi.h [hunk 7]
```diff
@@ -105,14 +105,6 @@ class AyonApi {
          */
         std::pair<std::string, std::string> getAssetIdent(const nlohmann::json &uriResolverRespone);
 
-        /**
-         * @brief this function loads all needed varible into the class \n
-         * this will allso be called by the constructor
-         *
-         * @return
-         */
-        bool loadEnvVars();
```
Comment (Lypsolon) [inline src/AyonCppApi/AyonCppApi.h:114]: Was load envvars always not implemented? I don't see you removing the implementation.

FYI; I'm only doing this review on github web so maybe i just overlooked it.

File: src/AyonCppApi/AyonCppApi.cpp [hunk 8]
```diff
@@ -32,57 +32,228 @@
...
-        std::filesystem::create_directories(logFilePath.parent_path());
-    }
+        if (inPath.is_relative()) {
+            logPath = std::filesystem::weakly_canonical(inPath);
+        }
+        if (!inPath.has_parent_path()) {
+            // if the input path is just an filename we will just throw it into tmp
+            logPath = std::filesystem::temp_directory_path() / inPath;
+        }
+        // we allways want the data to be a json, so we just enforce it.
```
Comment (philippe-ynput) [inline src/AyonCppApi/AyonCppApi.cpp]:
```suggestion
        // we always want the data to be a json, so we just enforce it.
```

File: src/AyonCppApi/AyonCppApi.cpp [hunk 9]
```diff
@@ -32,57 +32,228 @@
...
+
+    if (isSSL()) {
+        try {
+            std::string opensslDirCLI = getOpenSSLDirByCLI();
+
+            #ifdef _WIN32
+            std::string certFileCLI = opensslDirCLI + "\\cert.pem";
+            #else
+            std::string certFileCLI = opensslDirCLI + "/cert.pem";
+            #endif
```
Comment (philippe-ynput) [inline src/AyonCppApi/AyonCppApi.cpp]: Shouldn't we use std::filesystem::path to handle the multi-platform case here (and wherever applicable) ?

```suggestion
            std::filesystem::path opensslDirCLI(getOpenSSLDirByCLI());
            opensslDirCLI =/ "cert.pem";
            std::string certFileCLI = opensslDirCLI.string()
```

File: src/AyonCppApi/AyonCppApi.cpp [hunk 10]
```diff
@@ -116,7 +287,7 @@ AyonApi::rootReplace(const std::string &rootLessPath) {
                 return rootedPath;
             }
             catch (std::out_of_range &e) {
-                m_Log->warn("AyonApi::rootedPath error acured {}, list off available root replace str: ");
+                m_Log->warn("AyonApi::rootedPath error acured {}, list off available root replace str: ", e.what());
```
Comment (philippe-ynput) [inline src/AyonCppApi/AyonCppApi.cpp:264]:
```suggestion
                m_Log->warn("AyonApi::rootedPath error occured {}, list off available root replace str: ", e.what());
```

**Review by philippe-ynput — CHANGES_REQUESTED** [review]
Looking good overall, just a few minor things to tighten up. 👍

File: src/AyonCppApi/AyonCppApi.cpp (hunk 3 above)
Comment (philippe-ynput) [reply src/AyonCppApi/AyonCppApi.cpp]: I agree with @Lypsolon. The `getenv` should come first.

File: src/AyonCppApi/AyonCppApi.cpp (hunk 6 above)
Comment (philippe-ynput) [reply src/AyonCppApi/AyonCppApi.cpp:748]: I don't think there is anything to gain here.

File: src/AyonCppApi/AyonCppApi.cpp (hunk 10 above)
Comment (BigRoy) [reply src/AyonCppApi/AyonCppApi.cpp:264]: The `off` here is also a typo:
```suggestion
                m_Log->warn("AyonApi::rootedPath error occured {}, list of available root replace str: ", e.what());
```

**Review by MustafaJafar — APPROVED** [review]
It works on my side.
I was able to build and ayon-cpp-api and run my [cpp example](https://github.com/MustafaJafar/ayon-recipes/tree/main/test_cpp_api) using API Key. 
```
AYON_SERVER_URL=http://192.168.1.12:5000
AYON_API_KEY=veryinsecureapikey
```

I didn't test building the resolver using the branch though.

File: src/AyonCppApi/AyonCppApi.cpp (hunk 9 above)
Comment (tadeas-hejnic) [reply src/AyonCppApi/AyonCppApi.cpp]:
```suggestion
            std::filesystem::path opensslDirCLI(getOpenSSLDirByCLI());
            opensslDirCLI /= "cert.pem";
            std::string certFileCLI = opensslDirCLI.string()
```

File: src/AyonCppApi/AyonCppApi.cpp [hunk 11]
```diff
@@ -32,57 +32,224 @@
...
+            std::filesystem::create_directories(logPath.parent_path());
+        }
+    }
+    m_Log = std::make_shared<AyonLogger>(AyonLogger::getInstance(logPath.string()));
+    m_Log->LogLevelWarn();
 
     m_Log->info(m_Log->key("AyonApi"), "Init AyonServer httplib::Client");
     m_AyonServer = std::make_unique<httplib::Client>(m_serverUrl);
-    m_AyonServer->set_bearer_token_auth(m_authKey);
+    std::cout << "After creating httplib::Client - " << m_serverUrl << std::endl;
```
Comment (BigRoy) [inline src/AyonCppApi/AyonCppApi.cpp]: Should this go through the logger too? Or is there a reason this and further down use `std::cout` instead?

File: src/AyonCppApi/AyonCppApi.cpp [hunk 12]
```diff
@@ -28,61 +27,207 @@
 #include <vector>
 
 #include <cstdlib>
+#include <dlfcn.h>
```
Comment (MustafaJafar) [inline src/AyonCppApi/AyonCppApi.cpp:30]: When I was testing building USD resolver with https://github.com/ynput/ayon-usd-resolver/pull/46
I got this error for this lib: 
```
E:/Ynput/ayon-usd-resolver/ext/ayon-cpp-api/src/AyonCppApi/AyonCppApi.cpp:30:10: fatal error: dlfcn.h: No such file or directory
   30 | #include <dlfcn.h>
      |          ^~~~~~~~~
compilation terminated.
```

~~Is it expected to have this lib installed on my own?~~, it's a Linux thing.
~~_This error can be possibly from my local changes._~~

Comment (MustafaJafar) [reply src/AyonCppApi/AyonCppApi.cpp:30]: AI can be cool 😅 ..  

In Windows C++ development, the error occurs because <dlfcn.h> is a POSIX (Linux/Unix) header and is not part of the standard Windows SDK or the C++ Standard Library.

**Comment by MustafaJafar** [comment]
For reference, I ger this error when running build `python AyonBuild.py --runStageGRP CleanBuild`

```
CMake errors:
Error at build/src/AyonCppApi/cmake_install.cmake:55 (file):
  file INSTALL cannot find
  "E:/Ynput/ayon-recipes/test_cpp_api/ext/ayon-cpp-api/build/src/AyonCppApi/Release/AyonCppApi.lib":
  File exists.
Call Stack (most recent call first):
  build/cmake_install.cmake:47 (include)
```

**Comment by tadeas-hejnic** [comment]
> For reference, I ger this error when running build `python AyonBuild.py --runStageGRP CleanBuild`
> 
> ```
> CMake errors:
> Error at build/src/AyonCppApi/cmake_install.cmake:55 (file):
>   file INSTALL cannot find
>   "E:/Ynput/ayon-recipes/test_cpp_api/ext/ayon-cpp-api/build/src/AyonCppApi/Release/AyonCppApi.lib":
>   File exists.
> Call Stack (most recent call first):
>   build/cmake_install.cmake:47 (include)
> ```

It is not prepared for a standalone build, now it can be build only together with the resolver... It was a bit hot fix, but it is tested and it is working also on a client side. So the main issue of this PR (ssl connection) is fixed.

**Comment by MustafaJafar** [comment]
> It is not prepared for a standalone build, now it can be build only together with the resolver... It was a bit hot fix, but it is tested and it is working also on a client side. So the main issue of this PR (ssl connection) is fixed.

Are we interested in allowing standalone builds? I'm not sure if it's going to be used anywhere but in the USD resolver.

**Comment by tadeas-hejnic** [comment]
> > It is not prepared for a standalone build, now it can be build only together with the resolver... It was a bit hot fix, but it is tested and it is working also on a client side. So the main issue of this PR (ssl connection) is fixed.
> 
> Are we interested in allowing standalone builds? I'm not sure if it's going to be used anywhere but in the USD resolver.

Based on the conversation on discord, the repos should be probably merged into one, so cpp-api won't be standalone anymore.

**Review by philippe-ynput — APPROVED** [review]
